### ISSUE TITLE
Doesn't run out of the box

### ISSUE THREAD

**Issue by atesgoral** [RestComm/jss7.examples#1]
Getting error:

> Non-resolvable parent POM: Could not find artifact org.mobicents:mobicents-parent:pom:2.23-SNAPSHOT in mobicents-public-repository-group (http://oss.sonatype.org/content/groups/public/) and 'parent.relativePath' points at wrong local POM @ line 5, column 10 -> [Help 2]

**Comment by vetss** [comment]
Hello @atesgoral 

this repo contnains very old code that is already incompatible with the JSS7 latest code.
The code with same functionality you can find here:
https://github.com/RestComm/jss7/tree/master/map/load

**Comment by atesgoral** [comment]
@vetss Thanks a lot!
